version: 0.0
os: linux # ububtu를 사용할 경우 linux로 설정

hooks:
  # During the AfterInstall deployment lifecycle event, run the commands
  #   in the script specified in "location".
  AfterInstall:
    - location: scripts/handle-existing-docker-container.sh
      timeout: 60
      runas: ubuntu
    - location: scripts/select-deploy-env.sh
      timeout: 180
      runas: ubuntu
