server:
  port: ${BASE_PORT}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # sql show
        format_sql: true # sql show pretty

  output:
    ansi:
      enabled: never

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expire:
    access_hour: ${EXPIRE_HOUR_OF_ACCESS}
    refresh_day: ${EXPIRE_DAY_OF_REFRESH}
  test_token: ${TEST_TOKEN}

springdoc:
  swagger-ui:
    path: /swagger # swagger-ui 접근 경로에 대한 별칭. http://도메인:포트번호/{입력한 path}로 swagger-ui 접속 가능
    operations-sorter: method # method 순으로 정렬
  default-produces-media-type: application/json