spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # sql show
        format_sql: true # sql show pretty

  redis:
    host: ${DEV_REDIS_HOST}
    port: ${DEV_REDIS_PORT}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expire:
    access_hour: ${EXPIRE_HOUR_OF_ACCESS}
    refresh_day: ${EXPIRE_DAY_OF_REFRESH}