spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # sql show
        format_sql: true # sql show pretty

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expire_day:
    access: ${EXPIRE_DAY_OF_ACCESS}
    refresh: ${EXPIRE_DAY_OF_REFRESH}