sudo docker pull $DOCKER_REPOSITORY_URL:dev

if [ "$(docker ps -q -f name=$DOCKER_DEV_CONTAINER_NAME)" ]; then
  echo "Stopping container: $DOCKER_DEV_CONTAINER_NAME"
  sudo docker stop $DOCKER_DEV_CONTAINER_NAME
else
  echo "Container $DOCKER_DEV_CONTAINER_NAME is not running."
fi

sudo docker rm $DOCKER_DEV_CONTAINER_NAME

sudo docker run --name $DOCKER_DEV_CONTAINER_NAME \
-e DEV_REDIS_HOST=$DEV_REDIS_HOST \
-e DEV_REDIS_PORT=$DEV_REDIS_PORT \
-e DEV_DB_URL=$DEV_DB_URL \
-e DEV_DB_USERNAME=$DEV_DB_USERNAME \
-e DEV_DB_PASSWORD=$DEV_DB_PASSWORD \
-e JWT_SECRET=$JWT_SECRET \
-e EXPIRE_HOUR_OF_ACCESS=$EXPIRE_HOUR_OF_ACCESS \
-e EXPIRE_DAY_OF_REFRESH=$EXPIRE_DAY_OF_REFRESH \
$DOCKER_REPOSITORY_URL:dev