name: Devolpe project build and deploy

on:
  pull_request:
    branches: [ "develop" ] # develop브랜치의 PR에 대해서 trigger됨.

jobs:
  build_and_deploy: # 빌드하고 배포하기
    # if: github.event.pull_request.merged == true # PR이 머지되었을 때만 실행.
    
    runs-on: ubuntu-latest # 우분투 최신 버전에서 실행됨.
    permissions:
      contents: read # 내용 읽기만 가능함.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build -x test
      shell: bash

    - name: check is there .jar file
      run: |
        cd ./build/libs
        ls -a
      shell: bash

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx # 빌드킷 빌더 인스턴스 만들기.
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push # 이미지를 빌드하고, Docker Hub에 푸시하기.
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/scrap2024:latest
