name: Only Allow merge from develop to main

on:
  pull_request:
    branches: [ main ]

jobs:
  check-compare-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo current branch
        run: |
          echo "base branch = $GITHUB_BASE_REF"
          echo "head branch = $GITHUB_HEAD_REF"

      - name: only allow merge main<-develop # PR 소스 브랜치가 develop일 경우 성공, 그 외의 브랜치면 실패
        run: |
          if [ "$GITHUB_HEAD_REF" != "develop" ]; then
            echo "Pull requests to main must come from develop branch."
            exit 1
          fi