name: Only Allow merge from develop to main

on:
  pull_request:
    branches: [ main ]

jobs:
  check-compare-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check compare branch
        run: |
          # PR 소스 브랜치가 develop일 경우, 성공 그 외의 브랜치면 실패
          if: github.event.pull_request.head.ref != 'develop'
          run:|
          echo "Pull requests to main must come from develop branch."
          exit 1
